### ISSUE TITLE
GitReleases class functions won't write pandas datagrams

### ISSUE THREAD

**Issue by 0x000eHx** [TUBAF-IFI-DiPiT/github2pandas#44]
My System:
Python 3.9.4, Windows 10 x64, using the "new" github token (style)

Hey,
the functions you declared inside the GitRelease() class (git_releases.py) won't write the pandas datagrams to harddrive on Windows 10.
I was wondering about the fact, that your Git_Releases_Example Jupyter Notebook won't output a pandas Datagram, but after I tried to use the functions to aggregate git commits/releases I faced the problem, that there was no output and the pandas datagram were empty while debugging.
`
GitReleases.generate_git_releases_pandas_tables(repo, default_data_folder)
git_releases = GitReleases.get_git_releases(default_data_folder)
`
git_releases is empty after running through this line of code.
After I downloaded the github2pandas package via pip / pipenv and used it inside my own code the execution is way to fast. As far as I have understood the functions should at least download the git repository you are trying to analyse. But there is no temporary folder with the git repo. Only the Repo.json file gets written inside the data folder.

I'm pretty sure the github repos I tried to analyse are valid and I can connect to them.
There is no exception raised while using your functions.

I guess that is not intentional, cause in the wiki the pandas datagram output files are already explained.
Can you fix this?
Tell me what I need to provide, if you need more infos to solve this crime x)

**Comment by MaximilianKarl** [comment]
Hi,

The notebook only writes a pandas datagram if there are any releases. Has your target repository releases? I jut made one for this repository and it worked on win 10.

The execution is not downloading the repository. It loads the informations on call.

I will test it with python 3.9.4. Are the issues, pull_request or version working for you?

**Comment by MaximilianKarl** [comment]
Working with python 3.9.4 too on my win 10.

Please paste your code. Then I can help you out.

**Comment by 0x000eHx** [comment]
Hey, I think it was my wrong doing here. I tried your example notebook code and had no output. Obviously cause your github2pandas Repo had no tags/releases back then.
Then I tried it with another example Repo. Github recommended me: [Mamba](https://github.com/mamba-org/mamba). This project had tags and releases, but they are kind of different to the releases a project like [Notepad++](https://github.com/notepad-plus-plus/notepad-plus-plus) and your repo has. I can't tell the difference. But analysing the Mamba Repo still won't produce any GitReleases output. Your repo and Notepad++ repo do produce pandas datagrams.

**Comment by MaximilianKarl** [comment]
The reason you got no output from Mamba is that they only use tags and not releases. We are currently only extracting releases and not tags.

**Comment by 0x000eHx** [comment]
Ok, that all there is to know. Thank you for clearing that issue :)

**Comment by MaximilianKarl** [comment]
@0x000eHx Tags are now included in commits table. (v.1.1.0)
