### ISSUE TITLE
Crash on large repositories

### ISSUE THREAD

**Issue by MaximilianKarl** [TUBAF-IFI-DiPiT/github2pandas#63]
github2pandas crashes when there are a lot of Issues and Pull requests.

Problem: maximum request for one user is reached!

**Comment by SebastianZug** [comment]
Repository aggregation includes many separate requests. How can we integrate a continuous monitoring of request limits here? If we check too often, we would reduce the effectiveness ...

**Comment by MaximilianKarl** [comment]
test comment

**Comment by MaximilianKarl** [comment]
fixed and will be published in v.2.0.0
